/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'

const AuthIndexLazyRouteImport = createFileRoute('/_auth/')()
const AuthAnalyticsLazyRouteImport = createFileRoute('/_auth/analytics')()
const AuthAgentsLazyRouteImport = createFileRoute('/_auth/agents')()
const AuthActivityLazyRouteImport = createFileRoute('/_auth/activity')()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexLazyRoute = AuthIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.index.lazy').then((d) => d.Route))
const AuthAnalyticsLazyRoute = AuthAnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.analytics.lazy').then((d) => d.Route),
)
const AuthAgentsLazyRoute = AuthAgentsLazyRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.agents.lazy').then((d) => d.Route))
const AuthActivityLazyRoute = AuthActivityLazyRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.activity.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexLazyRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthActivityLazyRoute
  '/agents': typeof AuthAgentsLazyRoute
  '/analytics': typeof AuthAnalyticsLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AuthActivityLazyRoute
  '/agents': typeof AuthAgentsLazyRoute
  '/analytics': typeof AuthAnalyticsLazyRoute
  '/': typeof AuthIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/activity': typeof AuthActivityLazyRoute
  '/_auth/agents': typeof AuthAgentsLazyRoute
  '/_auth/analytics': typeof AuthAnalyticsLazyRoute
  '/_auth/': typeof AuthIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/activity' | '/agents' | '/analytics'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/activity' | '/agents' | '/analytics' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/activity'
    | '/_auth/agents'
    | '/_auth/analytics'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activity': {
      id: '/_auth/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthActivityLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthActivityLazyRoute: typeof AuthActivityLazyRoute
  AuthAgentsLazyRoute: typeof AuthAgentsLazyRoute
  AuthAnalyticsLazyRoute: typeof AuthAnalyticsLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivityLazyRoute: AuthActivityLazyRoute,
  AuthAgentsLazyRoute: AuthAgentsLazyRoute,
  AuthAnalyticsLazyRoute: AuthAnalyticsLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
